### ISSUE TITLE
tacl import can't upload files larger than 1GB

### ISSUE THREAD

**Issue by huguesfontenelle** [unioslo/tsd-api-client#48] opened 2020-04-28 09:12 UTC
## Background

When trying to upload a file bigger than 1GB, it fails.

## Steps to reproduce

```
tacl --import /path/to/folder/big.file.gz
User > pXX-huguesfo
Password >
OTP > 123456
401 Client Error: Unauthorized for url: https://api.tsd.usit.no/v1/p66/files/stream//path/to/folder/big.file.gz?chunk=1
The request was unsuccesful. Exiting...
```

## Expected behavior

Big files should upload :-)

## Workaround

```
split -b 700M big.file.gz
```
Then uploading each one.
But given that each file must be uploaded individually (see bug #47 ), this takes time! 

## Version

v2.3.0

**Comment by huguesfontenelle** [comment] 2020-04-28 09:34
I tried splitting at `1G` and `1000M` but the upload failed. `700M` went fine, and a previous image of 810M also went through. `900M` is too big. Not sure what the exact cut-off is.

**Comment by leondutoit** [comment] 2020-04-28 09:36
Are you sure you have the latest version installed? I cannot reproduce this:
```
ldt:~ leondutoit$ tacl --import /Users/leondutoit/Downloads/Xcode_11.xip
User > p11-leoncd
Password >
OTP > 975443
Upload id: 5d22950a-b93a-4f70-a6ee-336e21ab301c
Progress |#                               | 3%
```

**Comment by leondutoit** [comment] 2020-04-28 09:37
^ That file is 7GB btw

**Comment by leondutoit** [comment] 2020-04-28 09:38
The URL in your example is wrong, and is what was fixed in the latest release: `https://api.tsd.usit.no/v1/p66/files/stream//path/to/folder/big.file.gz?chunk=1`

**Comment by huguesfontenelle** [comment] 2020-04-28 10:23
I've wiped out my install folder and re-installed, and ran into more bugs, one of which reminded me of recent python features. My "outdated" python is version 3.5.

I've now upgraded with python 3.7. Big files are now uploading properly, and therefore this is not a bug :-)

**Closed** 2020-05-05 11:44 UTC
